name: Deploy

on:
  workflow_call:

jobs:

  merge-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Merge branch master
      run: echo "Merge maste"

    - name: Branch Merge
      uses: everlytic/branch-merge@1.1.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: refs/heads/main
