name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: go build main.go

  # docker:
  #   needs: app
  #   uses: ./.github/workflows/docker.yml